Repository c2corg/c2c_ui, pull requests merged in 2022-12, with the labels that each got.

#3098 fix: typo prevents printing distance in meters
  src/components/tracking/TrackingDeviceActivityRow.vue
Labels: bug

#3106 feat: quick and dirty christmas decorations
  package-lock.json
  package.json
  src/assets/img/hat.png
  src/js/vue-plugins/christmas.js
  src/main.js
  src/views/Navigation.vue
  src/views/SideMenu.vue
Labels: enhancement

#3107 feat: add placeholder in description field for climbing activities
  src/views/wiki/edition/RouteEditionView.vue
Labels: enhancement

#3114 Yeti updates
  src/components/yeti/YetiMap.vue
  src/components/yeti/Yetix.vue
  src/components/yeti/map-layers/AvalancheBulletinsLayer.vue
Labels: bug

#3115 fix(markdown): add style to markdown content for better images placement
  src/components/generics/Markdown.vue
Labels: bug

#3123 Allow to open map feature in new tab/window
  src/components/map/OlMap.vue
Labels: enhancement

#3127 feat: add map button to edit OSM map
  src/components/map/OlMap.vue
Labels: enhancement

#3133 chore: hide trackers menu for now, for testing only
  vue.config.js
Labels: chore

#3137 i18n: add missing translation key
  src/views/user/TrackersView.vue
Labels: i18n

#3138 i18n: add missing key
  src/views/user/TrackersView.vue
Labels: i18n

#3136 chore: fix prettier configuration for .vue files
  .eslintrc.json
  .prettierignore
  package.json
  src/components/generics/Markdown.vue
  src/components/yeti/YetiMap.vue
  src/components/yeti/map-layers/FlowcaptLayer.vue
  src/components/yeti/map-layers/IconLayer.vue
  src/components/yeti/map-layers/NivosesLayer.vue
  src/components/yeti/map-layers/RommaLayer.vue
  src/views/document/utils/DocumentViewHeader.vue
  src/views/documents/utils/PrintButton.vue
  src/views/documents/utils/QueryItems.vue
  src/views/documents/utils/QueryTags.vue
Labels: chore

#3142 feat: rework layer selector
  src/assets/img/flags/README.md
  src/assets/img/flags/at.svg
  src/assets/img/flags/ch.svg
  src/assets/img/flags/es.svg
  src/assets/img/flags/fr.svg
  src/assets/img/flags/gb.svg
  src/assets/img/layers/at.jpg
  src/assets/img/layers/atortho.jpg
  src/assets/img/layers/esri.jpg
  src/assets/img/layers/fauna.jpg
  src/assets/img/layers/ign.jpg
  src/assets/img/layers/ignes.jpg
  src/assets/img/layers/ignesortho.jpg
  src/assets/img/layers/ignortho.jpg
  src/assets/img/layers/ignslopes.jpg
  src/assets/img/layers/opentopomap.jpg
  src/assets/img/layers/swisstopo.jpg
  src/assets/img/layers/swisstopoortho.jpg
  src/assets/img/layers/swisstoposlopes.jpg
  src/assets/img/layers/uk.jpg
  src/components/map/LayerButton.vue
  src/components/map/OlMap.vue
  src/components/map/map-layers.js
Labels: enhancement

#3150 feat: add ICGC maps
  src/assets/img/flags/catalonia.svg
  src/assets/img/layers/icgc.jpg
  src/assets/img/layers/icgcortho.jpg
  src/components/map/map-layers.js
  src/js/libs/ol.js
Labels: enhancement

#3151 i18n: ESRI i18n typos
  src/components/map/map-layers.js
Labels: i18n

#3152 i18n: fix ordnance survey key
  src/components/map/map-layers.js
Labels: i18n

#3154 i18n: fix ICGC key
  src/components/map/map-layers.js
Labels: i18n

#3157 feat(map): enhance biodivsport areas styling to match swisstopo layers
  src/components/map/map-utils.js
Labels: enhancement

#3156 fix(map): valid parameters for swiss protection areas
  src/components/map/map-layers.js
Labels: bug

#3158 feat(map): allow to configure map layers opacity
  src/components/map/LayerButton.vue
  src/components/map/OlMap.vue
  src/components/map/map-layers.js
  src/js/vue-plugins/font-awesome-config.js
  src/views/Navigation.vue
  src/views/portals/DashboardView.vue
Labels: enhancement

#3167 revert: #3106 (Christmas decorations)
  package-lock.json
  package.json
  src/assets/img/hat.png
  src/js/vue-plugins/christmas.js
  src/main.js
  src/views/Navigation.vue
  src/views/SideMenu.vue
Labels: revert

#3165 revert: #3091
  src/components/generics/Markdown.vue
Labels: revert

#3166 chore: run npm audit fix
  package-lock.json
Labels: security, chore

#3168 perf: remove WIP route
  src/js/vue-plugins/router.js
  src/views/static-views/WorkInProgressView.vue
Labels: perf

#3169 feat: rework auth gards
  src/components/generics/buttons/LoginButton.vue
  src/js/vue-plugins/router.js
  src/views/Navigation.vue
  src/views/user/LoginView.vue
  src/views/wiki/edition/utils/document-edition-view-mixin.js
Labels: enhancement

#3170 fix(map): handle layer selector size when elevation profile is shown in fullscreen mode
  src/components/map/OlMap.vue
  src/views/document/utils/boxes/MapBox.vue
Labels: bug

#3172 feat: handle disabled apps
  src/views/user/TrackersView.vue
Labels: enhancement

#3176 feat: documents query bar position on mobile
  src/views/documents/DocumentsView.vue
  src/views/documents/utils/PageSelector.vue
  src/views/documents/utils/QueryItems.vue
Labels: enhancement
