Repository c2corg/c2c_ui, pull requests merged in 2022-10, with the labels that each got.

#2976 Use github auto-generated release notes
  .github/release.yml
  .github/workflows/changelog.yml
  .github/workflows/ci.yml
Labels: chore

#2978 Update changelog source, redirect to releases for releases after v7.6.17
  CHANGELOG.md
Labels: chore

#2996 Use external fit parser
  package-lock.json
  package.json
  src/js/fit/FIT.js
Labels: dependencies

#2997 chore: code cleanup
  src/js/config.js
  src/views/Advertisement.vue
  src/views/document/utils/boxes/CommentsBox.vue
Labels: chore

#2998 build: specify vue target in jsconfig
  jsconfig.json
Labels: chore

#2999 build: allow to use docker production build with demo configuration
  src/js/config.js
  src/views/Navigation.vue
  src/views/document/utils/boxes/CommentsBox.vue
  vue.config.js
Labels: chore

#3008 [YETI] Fix performance issue
  src/components/yeti/YetiMap.vue
Labels: enhancement

#3009 feat(statistics): fix NaN when there is no outing yet
  src/views/portals/outings-stats/OutingsStatsView.vue
Labels: enhancement

#3013 feat(cps): order pictures by association date
  src/views/portals/SophiePictureContestView.vue
Labels: enhancement

#2909 YETI: new layers
  src/components/yeti/YetiMap.vue
  src/components/yeti/Yetix.vue
  src/components/yeti/map-layers/AvalancheBulletinsLayer.vue
  src/components/yeti/map-layers/FlowcaptLayer.vue
  src/components/yeti/map-layers/IconLayer.vue
  src/components/yeti/map-layers/NivosesLayer.vue
  src/components/yeti/map-layers/RommaLayer.vue
  src/components/yeti/map-layers/layer.js
Labels: enhancement

#3014 chore: generate release notes automatically with release creation
  .github/workflows/ci.yml
Labels: chore, github_actions

#3017 chore: use c2corg/transifex-pull-request-action@v5
  .github/workflows/retrieve-i18n.yml
Labels: chore

#3022 Correctly display f-number and exposure time
  src/components/generics/DocumentField.vue
  src/js/constants/fieldsProperties.json
  src/views/document/utils/field-viewers/FieldView.vue
Labels: bug

#3025 Add empty screen for outings statistics
  src/views/portals/outings-stats/OutingsStatsView.vue
Labels: enhancement

#3030 feat(i18n): add translation for account page title
  src/views/user/AccountView.vue
Labels: enhancement
