Repository c2corg/c2c_ui, pull requests merged in 2022-11, with the labels that each got.

#3005 Add "ignore year" option in outing date filter
  src/js/constants/documentsProperties.json
  src/js/constants/fieldsProperties.json
  src/translations/fr.json
  src/views/documents/utils/DatesQueryItem.vue
  src/views/documents/utils/QueryItems.vue
Labels: enhancement

#3051 feat: add multi-search dropdown in mobile
  src/components/generics/DropdownButton.vue
  src/views/documents/utils/AssociationQueryItem.vue
  src/views/documents/utils/QueryItems.vue
  src/views/documents/utils/QueryTags.vue
Labels: enhancement

#3059 fix: handle both MultiLineString and LineString geometries for elevation profile
  src/views/document/utils/boxes/ElevationProfile.vue
Labels: bug

#3060 fix: CPS 2022
  src/views/portals/SophiePictureContestView.vue
Labels: bug

#3063 fix: handle initial undefined value in outing statistics
  src/views/portals/outings-stats/OutingsStatsView.vue
Labels: bug

#3071 fix: avoid date inconsistency for several days outing
  src/views/wiki/edition/OutingEditionView.vue
Labels: bug

#3074 feat: improve naming of downloaded traces
  src/views/document/utils/boxes/MapBox.vue
Labels: enhancement

#2240 Print a list of documents in PDF
  src/assets/sass/helpers.scss
  src/components/generics/pretty-links/PrettyBookLink.vue
  src/components/generics/pretty-links/PrettyOutingLink.vue
  src/components/generics/pretty-links/PrettyRouteLink.vue
  src/components/generics/pretty-links/PrettyWaypointLink.vue
  src/components/generics/pretty/PrettyBook.vue
  src/components/generics/pretty/PrettyOuting.vue
  src/components/generics/pretty/PrettyRoute.vue
  src/components/generics/pretty/PrettyWaypoint.vue
  src/components/map/OlMap.vue
  src/js/view-mode-mixin.js
  src/js/vue-plugins/font-awesome-config.js
  src/js/vue-plugins/router.js
  src/views/document/utils/DocumentViewHeader.vue
  src/views/document/utils/GotopButton.vue
  src/views/document/utils/boxes/ImagesBox.vue
  src/views/document/utils/document-view-mixin.js
  src/views/documents/DocumentsPrintingView.vue
  src/views/documents/utils/PrintButton.vue
  src/views/documents/utils/PrintingOptions.vue
  src/views/documents/utils/PrintingSummary.vue
  src/views/documents/utils/QueryItems.vue
Labels: enhancement

#3082 bug(i18n): add missing i18n keys
  src/views/documents/DocumentsPrintingView.vue
  src/views/documents/utils/PrintingOptions.vue
  src/views/documents/utils/PrintingSummary.vue
Labels: bug, i18n

#3083 bug(i18n): add one more missing key
  src/views/document/utils/GotopButton.vue
Labels: bug, i18n

#3038 feat: connect with tracking devices to retrieve GPS data
  .eslintrc.json
  package-lock.json
  package.json
  src/assets/img/tracking/decathlon.png
  src/assets/img/tracking/garmin.png
  src/assets/img/tracking/polar.png
  src/assets/img/tracking/strava.png
  src/assets/img/tracking/suunto.png
  src/assets/sass/main.scss
  src/components/cards/FeedCard.vue
  src/components/cards/OutingCard.vue
  src/components/cards/XreportCard.vue
  src/components/datatable/DocumentsTable.vue
  src/components/datatable/cell-renderers/OutingDate.vue
  src/components/generics/DocumentField.vue
  src/components/generics/icons/IconHeightDiffUp.vue
  src/components/generics/inputs/InputDate.vue
  src/components/generics/inputs/InputDatetime.vue
  src/components/image-viewer/ImageInfo.vue
  src/components/map/GpsFileUpload.vue
  src/components/map/GpsUploadModal.vue
  src/components/map/OlMap.vue
  src/components/tracking/ApplicationCard.vue
  src/components/tracking/TrackingDeviceActivities.vue
  src/components/tracking/TrackingDeviceActivityRow.vue
  src/components/yeti/SubPanelCourse.vue
  src/components/yeti/map-layers/AvalancheBulletinsLayer.vue
  src/js/apis/biodivsports-service.js
  src/js/apis/respectercestproteger-service.js
  src/js/apis/tracking-service.js
  src/js/upload-file.js
  src/js/vue-plugins/date-utils.js
  src/js/vue-plugins/document-utils.js
  src/js/vue-plugins/font-awesome-config.js
  src/js/vue-plugins/router.js
  src/js/vue-plugins/user.js
  src/translations/fixed_strings_manual.vue
  src/views/Navigation.vue
  src/views/document/utils/DocumentVersionBanner.vue
  src/views/document/utils/DocumentViewHeader.vue
  src/views/portals/DashboardView.vue
  src/views/user/TrackersExchangeTokenView.vue
  src/views/user/TrackersView.vue
  src/views/wiki/edition/OutingEditionView.vue
  src/views/wiki/edition/utils/FormInput.vue
  src/views/wiki/edition/utils/MapInputRow.vue
  src/views/wiki/edition/utils/README.md
  src/views/wiki/edition/utils/document-edition-view-mixin.js
  vue.config.js
Labels: enhancement
