Repository c2corg/c2c_ui, pull requests merged in 2023-03, with the labels that each got.

#3344 fix: change folding icon orientation
  src/components/generics/AccordionItem.vue
Labels: bug

#3343 feat: add link to CC licenses in image type field
  src/components/generics/DocumentField.vue
Labels: enhancement

#3345 fix: add feedback when account edition form is submitted and email link followed
  src/js/vue-plugins/font-awesome-config.js
  src/views/user/AccountView.vue
  src/views/user/LoginView.vue
  src/views/user/utils/FormSubmitSuccessIndicator.vue
Labels: bug

#3346 feat: add Coros devices
  src/assets/img/tracking/coros.png
  src/views/user/TrackersView.vue
  vue.config.js
Labels: enhancement

#3349 feat: trackers view enhancements
  src/components/generics/icons/SpinnerIcon.vue
  src/components/tracking/ApplicationCard.vue
  src/components/tracking/TrackingDeviceActivities.vue
  src/components/tracking/TrackingDeviceActivity.vue
  src/js/vue-plugins/document-utils.js
  src/js/vue-plugins/font-awesome-config.js
  src/views/user/TrackersExchangeTokenView.vue
  src/views/user/TrackersView.vue
Labels: enhancement

#3350 feat: add license information when printing
  src/assets/sass/helpers.scss
  src/js/vue-plugins/document-utils.js
  src/views/document/AreaView.vue
  src/views/document/ArticleView.vue
  src/views/document/BookView.vue
  src/views/document/ImageView.vue
  src/views/document/OutingView.vue
  src/views/document/RouteView.vue
  src/views/document/WaypointView.vue
  src/views/document/XreportView.vue
  src/views/document/utils/DocumentPrintLicense.vue
  src/views/document/utils/boxes/LicenseBox.vue
  src/views/document/utils/document-view-mixin.js
Labels: enhancement

#3354 style: code cleanup
  src/components/generics/DocumentField.vue
  src/components/generics/inputs/InputActivity.vue
  src/components/generics/modals/ModalConfirmation.vue
  src/components/helper/HelperWindow.vue
  src/components/map/BiodivInformation.vue
  src/views/document/utils/DocumentVersionBanner.vue
  src/views/document/utils/LowDocumentQualityBanner.vue
  src/views/document/utils/boxes/CommentsBox.vue
  src/views/document/utils/windows/DeleteDocumentWindow.vue
  src/views/document/utils/windows/DeleteLocaleWindow.vue
  src/views/document/utils/windows/RevertVersionWindow.vue
  src/views/document/utils/windows/TranslateWindow.vue
  src/views/documents/utils/QuerySortDropdown.vue
  src/views/static-views/TopoguideView.vue
  src/views/wiki/DiffView.vue
  src/views/wiki/WhatsNewView.vue
  src/views/wiki/edition/ImageEditionView.vue
  src/views/wiki/edition/OutingEditionView.vue
  src/views/wiki/edition/utils/CotometerWindow.vue
  src/views/wiki/edition/utils/MapInputRow.vue
  src/views/wiki/utils/HistoryViewLinks.vue
  tools/extract-messages.js
Labels: style

#3355 feat: use specific article for bouldering
  src/views/document/RouteView.vue
Labels: enhancement

#3370 fix: invalid URL when ctrl+clicking a document in map
  src/components/map/OlMap.vue
Labels: bug

#3385 feat: Add association's logo
  src/assets/img/logo_asso.svg
Labels: enhancement

#3384 feat(yeti): Elevation profile: new tool and improvements
  src/assets/sass/helpers.scss
  src/components/yeti/DropdownContent.vue
  src/components/yeti/ElevationProfile.vue
  src/components/yeti/Info.vue
  src/components/yeti/SimplifyTool.vue
  src/components/yeti/SubPanelCourse.vue
  src/components/yeti/ValidationButton.vue
  src/components/yeti/YetiMap.vue
  src/components/yeti/Yetix.vue
  src/components/yeti/map-layers/AvalancheBulletinsLayer.vue
  src/components/yeti/map-layers/RouteLayer.vue
  src/views/portals/YetiView.vue
Labels: enhancement

#3335 feat: New home - Dispatch display parameters buttons
  src/assets/sass/variables.scss
  src/components/cards/FeedCard.vue
  src/components/cards/utils/CardRow.vue
  src/components/generics/icons/IconYeti.vue
  src/components/yeti/map-layers/IconLayer.vue
  src/js/apis/forum.js
  src/js/vue-plugins/router.js
  src/views/portals/DashboardView.vue
  src/views/portals/FeedView.vue
  src/views/portals/HomeBanner.vue
  src/views/portals/HomeView.vue
  src/views/portals/utils/BoardAnnoucementWidget.vue
  src/views/portals/utils/DashboardArticleLink.vue
  src/views/portals/utils/DashboardArticlesList.vue
  src/views/portals/utils/DashboardImagesGallery.vue
  src/views/portals/utils/DashboardLink.vue
  src/views/portals/utils/DashboardOutingLink.vue
  src/views/portals/utils/DashboardOutingsList.vue
  src/views/portals/utils/DashboardRoutesList.vue
  src/views/portals/utils/ForumWidget.vue
  src/views/portals/utils/UsefulLinks.vue
Labels: enhancement
