Repository c2corg/c2c_ui, pull requests merged in 2023-01, with the labels that each got.

#3171 feat: enable trackers menu for everyone
  src/views/Navigation.vue
  vue.config.js
Labels: enhancement

#3185 fix: use another approach to avoid multiline buttons on mobile
  src/js/vue-plugins/font-awesome-config.js
  src/views/documents/utils/LoadUserPreferencesButton.vue
  src/views/documents/utils/PrintButton.vue
  src/views/documents/utils/QueryItems.vue
Labels: bug

#3184 feat(yeti): add avalanche bulletins for Italy
  src/components/yeti/map-layers/AvalancheBulletinsLayer.vue
Labels: enhancement

#3186 chore: no more legacy build
  babel.config.js
  package.json
Labels: chore

#3188 feat: add Slovenian as API language
  src/js/apis/c2c/index.js
  src/js/constants/common.json
  src/js/vue-plugins/gettext-plugin.js
  src/views/wiki/edition/utils/document-edition-view-mixin.js
Labels: enhancement, i18n

#3197 chore: typo
  src/components/map/OlMap.vue
Labels: chore

#3198 feat: use fixed-width icons in menus
  src/components/generics/icons/IconForum.vue
  src/components/generics/icons/IconHelp.vue
  src/components/generics/icons/IconTopoguide.vue
  src/components/generics/icons/document/IconArea.vue
  src/components/generics/icons/document/IconArticle.vue
  src/components/generics/icons/document/IconBook.vue
  src/components/generics/icons/document/IconDocument.vue
  src/components/generics/icons/document/IconImage.vue
  src/components/generics/icons/document/IconMap.vue
  src/components/generics/icons/document/IconOuting.vue
  src/components/generics/icons/document/IconProfile.vue
  src/components/generics/icons/document/IconRoute.vue
  src/components/generics/icons/document/IconWaypoint.vue
  src/components/generics/icons/document/IconXreport.vue
  src/views/Navigation.vue
  src/views/SideMenu.vue
Labels: enhancement

#3203 Thumbnail images should appear above section titles
  src/components/generics/Markdown.vue
Labels: bug

#3111 Support webp and avif format via <picture>
  package-lock.json
  package.json
  patches/swiper+6.8.4.patch
  src/components/association-editor/AssociationImageLink.vue
  src/components/gallery/Gallery.vue
  src/components/generics/Markdown.vue
  src/components/generics/Thumbnail.vue
  src/components/image-viewer/ImageViewer.vue
  src/js/image-urls.js
  src/views/document/ImageView.vue
  src/views/document/utils/document-view-mixin.js
  src/views/documents/utils/ImageCards.vue
  src/views/portals/SophiePictureContestView.vue
  src/views/wiki/DiffView.vue
  src/views/wiki/edition/ImageEditionView.vue
  vue.config.js
Labels: enhancement

#3219 fix: includes patches folder in dockerfile
  Dockerfile
Labels: bug

#3222 fix: layer selector height on documents list
  src/components/map/OlMap.vue
Labels: bug

#3223 fix(yeti): when validUntil date is expired, warn user
  src/components/yeti/map-layers/AvalancheBulletinsLayer.vue
Labels: bug, yeti

#3225 chore(refactor): avoid using type as variable name in template
  src/components/yeti/SubPanelCourse.vue
Labels: refactor, chore

#3224 fix(i18n): add key for title
  src/components/yeti/YetiMap.vue
Labels: bug, i18n

#3227 feat: enhance fold section icon
  src/components/generics/AccordionItem.vue
  src/views/document/utils/boxes/RoutesBox.vue
  src/views/document/utils/field-viewers/MarkdownSection.vue
Labels: enhancement

#3228 feat: add edit document link in toolbox
  src/components/generics/icons/IconQuality.vue
  src/components/generics/icons/IconWaypointType.vue
  src/views/document/utils/boxes/AssociatedDocuments.vue
  src/views/document/utils/boxes/ToolBox.vue
  src/views/document/utils/boxes/ToolBoxButton.vue
Labels: enhancement

#3233 fix: use client ids from matching environment
  src/views/user/TrackersView.vue
  vue.config.js
Labels: bug, chore

#3236 bug: thumbnails in Concours Photo Sophie pages
  src/views/portals/SophiePictureContestView.vue
Labels: bug

#3238 feat: allow shorter strings when using CJK characters
  src/js/constants/Field.js
  src/js/constants/fieldsProperties.json
Labels: enhancement, i18n

#3239 feat: add section in activity trackers page to promote Outdoovision
  src/assets/img/outdoorvision.svg
  src/views/user/TrackersView.vue
Labels: enhancement

#3257 fix(yeti): performance improvements
  src/components/yeti/map-layers/AreaLayer.vue
  src/components/yeti/map-layers/AvalancheBulletinsLayer.vue
  src/js/libs/ol.js
Labels: bug

#3258 chore: follow & check conventional commits specification
  .github/semantic-labels.yml
  .github/workflows/semantic-pull-request.yml
Labels: chore

#3259 feat: simplify sign in view
  src/views/user/LoginView.vue
  src/views/user/utils/BaseForm.vue
  src/views/user/utils/FormField.vue
Labels: enhancement
