Repository c2corg/c2c_ui, pull requests merged in 2024-11, with the labels that each got.

#4117 feat(yeti): Some fixes and storing layers
  src/components/yeti/DropdownContent.vue
  src/components/yeti/EditModeButton.vue
  src/components/yeti/SimplifyTool.vue
  src/components/yeti/SubPanelCourse.vue
  src/components/yeti/SubPanelLayers.vue
  src/components/yeti/YetiMap.vue
  src/components/yeti/Yetix.vue
  src/components/yeti/map-layers/AvalancheBulletinsLayer.vue
  src/components/yeti/map-layers/BaseLayers.vue
  src/components/yeti/map-layers/IconLayer.vue
  src/components/yeti/map-layers/OverlaysLayers.vue
  src/components/yeti/map-layers/RouteLayer.vue
  src/components/yeti/map-layers/SlopesLayers.vue
  src/views/portals/YetiView.vue
Labels: enhancement

#3846 feat: #3697 add waypoints external resources section
  src/js/constants/documentsProperties.json
  src/views/document/WaypointView.vue
  src/views/wiki/edition/WaypointEditionView.vue
Labels: enhancement

#4140 i18n: ensure YETI agreement translation is applied
  src/views/portals/YetiView.vue
Labels: i18n

#4141 chore: fix semantic PR allowed types configuration
  .github/workflows/semantic-pull-request.yml
Labels: chore
