Repository c2corg/c2c_ui, pull requests merged in 2024-03, with the labels that each got.

#3852 feat: Add avalanche bulletin info in toolbox
  package-lock.json
  package.json
  src/components/generics/icons/IconBra.vue
  src/components/generics/inputs/InputOrientation.vue
  src/components/yeti/map-layers/AvalancheBulletinsLayer.vue
  src/js/apis/yeti-service.js
  src/views/document/RouteView.vue
  src/views/document/utils/boxes/AvalancheBox.vue
  src/views/document/utils/boxes/MapBox.vue
  src/views/document/utils/document-view-mixin.js
Labels: enhancement

#3856 feat: Add total climb (denivelé) to single-line route display
  src/components/generics/pretty/PrettyRoute.vue
Labels: enhancement

#3893 refactor: babel-eslint is redundant with @babel/eslint-parser, and deprecated
  package-lock.json
  package.json
Labels: refactor

#3892 fix: Avoid 'Network error' notification when opening c2c with expired token
  src/js/apis/c2c/UserProfileService.js
  src/js/apis/c2c/index.js
  src/js/vue-plugins/user.js
  src/views/Navigation.vue
Labels: bug
