Repository c2corg/c2c_ui, pull requests merged in 2024-01, with the labels that each got.

#3662 feat: Minor change : Update ToolBox.vue
  src/views/document/utils/boxes/ToolBox.vue
Labels: enhancement

#3661 feat: Update TranslateWindow.vue
  src/views/document/utils/windows/TranslateWindow.vue
Labels: enhancement

#3786 feat: Add "Join us" button in navigation
  src/components/generics/icons/IconJoinUs.vue
  src/components/generics/links/JoinUsLink.vue
  src/js/vue-plugins/font-awesome-config.js
  src/views/Navigation.vue
Labels: enhancement

#3788 feat: Come back to standard logo
  src/views/Navigation.vue
  src/views/SideMenu.vue
Labels: enhancement

#3783 feat: #3755 add author in diaporama
  src/components/image-viewer/ImageInfo.vue
Labels: enhancement

#3779 fix: #2085 display GPS coordinate input
  src/views/wiki/edition/utils/MapInputRow.vue
Labels: bug

#3770 chore: #3768 use openresty debian bookworm as production base docker image
  Dockerfile
Labels: chore

#3803 fix(yeti): Use own WMS server
  src/components/yeti/map-layers/WinterRouteLayer.vue
Labels: bug

#3794 fix: #3571 recenter on map search. Supersedes #3787
  src/components/map/OlMap.vue
Labels: bug

#3811 feat: allow visible password
  src/views/user/utils/FormField.vue
Labels: enhancement
